---
# tasks file for elk
- include_tasks: packages.yml
  tags: packages

- include_tasks: elasticsearch.yml
  tags: elasticsearch

- include_tasks: mappings.yml
  tags: mappings

- include_tasks: logstash.yml
  tags: logstash

- include_tasks: kibana.yml
  tags: kibana

- include_tasks: nginx.yml
  when: elk_configure_nginx == true
  tags: nginx

- include_tasks: ufw.yml
  when: elk_configure_firewall == true
  tags: ufw

- include_tasks: snapshot.yml
  when: elk_elasticsearch_snapshot == true
  tags: snapshot

- include_tasks: curator.yml
  tags: curator.yml
