---
- name: Install httplib2
  apt:
    name: python-httplib2
    state: present


# mappings and index templates must be loaded another way
#- name: Set default ElasticSearch mappings for Logstash.
#  uri:
#    url: "http://localhost:9200/_template/logstash"
#    method: POST
#    body: "{{ lookup('file', 'elasticsearch-template-logstash-output.json') }}"
#    status_code: 200
#    body_format: json

#- name: Set default ElasticSearch mappings for Metricbeat.
#  uri:
#    url: "http://localhost:9200/_template/metricbeat"
#    method: POST
#    body: "{{ lookup('file', 'elasticsearch-template-metricbeat.json') }}"
#    status_code: 200
#    body_format: json

#- name: Set default ElasticSearch mappings for Filebeat.
#  uri:
#    url: "http://localhost:9200/_template/filebeat"
#    method: POST
#    body: "{{ lookup('file', 'elasticsearch-template-filebeat.json') }}"
#    status_code: 200
    # body_format: json
